### ISSUE TITLE
Object ReplicaSet not found in api on startup of deploytime exporter

### ISSUE THREAD

**Issue by willowmck** [redhat-cop/pelorus#186] opened 2020-09-03 13:41 UTC
See the following traceback when Pelorus exporter for deploy time starts -

```
Traceback (most recent call last):
  File "deploytime/app.py", line 106, in <module>
    REGISTRY.register(DeployTimeCollector(namespaces))
  File "/opt/app-root/lib64/python3.8/site-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/opt/app-root/lib64/python3.8/site-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "deploytime/app.py", line 23, in collect
    metrics = generate_metrics(self._namespaces)
  File "deploytime/app.py", line 78, in generate_metrics
    v1_replicationsets = dyn_client.resources.get(api_version='extensions/v1beta1', kind='ReplicaSet')
  File "/opt/app-root/lib64/python3.8/site-packages/openshift/dynamic/discovery.py", line 246, in get
    raise ResourceNotFoundError('No matches found for {}'.format(kwargs))
openshift.dynamic.exceptions.ResourceNotFoundError: No matches found for {'api_version': 'extensions/v1beta1', 'kind': 'ReplicaSet'}
```

**Comment by etsauer** [comment] 2020-09-03 13:55
@malacourse can you take a look?

**Comment by etsauer** [comment] 2020-09-03 13:58
@willowmck we just recently merged some code to handle these various types. I think the issue is that we didn't handle the cases that all clusters won't support all apiVersions. We'll need to do some exception handling in this block: https://github.com/redhat-cop/pelorus/blob/master/exporters/deploytime/app.py#L65-L80

**Comment by malacourse** [comment] 2020-09-03 14:03
I will add handling for this case.

**Comment by willowmck** [comment] 2020-09-03 14:16
Thanks guys for hopping on this one so quickly!  @etsauer I can wait for @malacourse fix as I wanted to add some debugging around the commit time exporter.

**Closed** 2020-09-15 18:02 UTC
Labels: bug
